apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: product-catalog

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: product-backend:1.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000

        env:

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: DB_PORT

        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: POSTGRES_DB

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: POSTGRES_PASSWORD
