services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    container_name: postgres-db
    
    env_file:
      - ./environments/local/.env

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"
        ]
  
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    container_name: flask-backend

    env_file:
      - ./environments/local/.env

    expose:
      - "5000"

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: react-frontend

    ports:
      - "5173:8080"

    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
