apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: product-catalog
  labels:
    app: postgres
    component: storage
    project: product-catalog

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
