apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - namespace.yaml

  - configmap.yaml
  - secret.yaml

  - api/backend-deployment.yaml
  - api/backend-service.yaml

  - web/frontend-deployment.yaml
  - web/frontend-service.yaml

  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-pvc.yaml

  - ingress.yaml

  # Network Policies
  - networkpolicy/default-deny-ingress.yaml
  - networkpolicy/default-deny-egress.yaml
  - networkpolicy/allow-dns.yaml
  - networkpolicy/allow-backend-postgres.yaml
  - networkpolicy/allow-postgres-ingress.yaml
  - networkpolicy/allow-frontend-backend.yaml
  - networkpolicy/allow-ingress-frontend.yaml
  - networkpolicy/allow-ingress-backend.yaml
