apiVersion: v1
kind: Secret

metadata:
  name: product-secret
  namespace: product-catalog
  labels:
    project: product-catalog
    component: secret

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
