apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: product-catalog
  labels:
    app: frontend
    component: web
    project: product-catalog

spec:
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 8080

  type: ClusterIP
