apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog

resources:
  - ../../base

images:
  - name: product-backend
    newName: anusree15/product-backend
    newTag: "1.0"
  - name: product-frontend
    newName: anusree15/product-frontend
    newTag: "1.0"
